### ISSUE TITLE
Adopt main branch workflow or update docs

### ISSUE THREAD

**Issue by sbs2001** [nexB/skeleton#12]
The README has the line which says `git merge skeleton/main --allow-unrelated-histories` . This fails because there is no `main` branch . Either update that line to `git merge skeleton/develop --allow-unrelated-histories` or create a main branch .

**Comment by majurg** [comment]
Good catch. We should be following `main` by default where possible. I will adjust this for this repo and update the docs.

**Comment by majurg** [comment]
@sbs2001 This repo now follows main by default on GH.
